### ISSUE TITLE
Negative Fuel Block

### ISSUE THREAD

**Issue by iFlySimX** [headwindsim/A339X#21] opened 2022-04-20 13:11 UTC
Hello! When loading up the MCDU, I get a negative Fuel Block as seen in the screenshot below.
![Screenshot (655)](https://user-images.githubusercontent.com/103451871/164237917-84648b48-84d5-4dce-87b9-f305f89e3383.png)

Steps to reproduce:

1. Load simbrief flight plan on the FlyPad.
2. Load the fuel based off of simbrief on the FlyPad.
3. Load the weight and pax on the MCDU.
4. Then when I go to INIT and load the weight and REQ the fuel block comes in negative.

**Comment by BigCow74** [comment] 2022-04-21 01:57
I know you already confirmed it, but here's another example just for reference
<img width="428" alt="mcdu-initb" src="https://user-images.githubusercontent.com/101572828/164356312-0080c3ba-4664-4e1c-bf05-03a03f03dd2c.png">
.

**Comment by TwattyBollox** [comment] 2022-12-09 20:49
@BigCow74 Hmmm ... I thought the max ZFW is 181 tonnes?
Similarly I believe the max TOW is 251, so the ZFW in your pic is a bit high it seems?

**Comment by BigCow74** [comment] 2022-12-09 23:25
> @BigCow74 Hmmm ... I thought the max ZFW is 181 tonnes? Similarly I believe the max TOW is 251, so the ZFW in your pic is a bit high it seems?

My aircraft is set for lbs and not kg. I'm a pain-in-the-ass American :)

**Comment by TwattyBollox** [comment] 2022-12-10 16:46
DOH! Apologies :¬)

**Comment by pennlio111** [comment] 2023-01-27 06:18
have the same bug; so it is just because of units?

**Comment by TwattyBollox** [comment] 2023-01-28 08:19
> have the same bug; so it is just because of units?

No, I was saying his fuel "looked way too high", but that's because he was using pounds and not kilos, so my 1000 kg is 2204.5 pounds on his display. The bug is nothing to do with that, it was just me making an error and forgetting some people use pounds :¬)

**Comment by Revyn112** [comment] 2023-02-06 17:25
Fixed with next stable release

**Closed by Revyn112** 2023-02-06 17:25 UTC
Labels: Class: Bug, Status: Confirmed
